[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 src/main.py"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
PORT = "8000"
PYTHON_VERSION = "3.11"
